### PR TITLE
Alternate monitoring

### LINKED ISSUE #10: Detect when a device goes offline
- [x]  Implement logic to compare current scan results with previous state
- [x] Implement heartbeat/ping monitoring to track device uptime
- [x]  Mark devices as offline if the heartbeat is missing or ping fails (Yellow 1 min Red 5 min? )
- [x]  Store offline events in the database log

### PR DESCRIPTION
**Pull request by hxkhan**
- Added functionality to check devices and adding them to OfflineEvents if not checked in within 3 minutes in `TrackerService.java`
- Implement restoration logic in existing scan and checkin queries that updates `OfflineEvents` for devices marked offline

closes #10

### CODE REVIEW

File: backend/src/main/java/kg16/demo/model/Services/ScanService.java [hunk 1]
```diff
@@ -31,13 +34,21 @@ public void upsertScan(String hostname, String ipAddress, String macAddress) {
...
-                                s.last_seen = NOW()
+                                s.last_seen = ?
                     WHEN NOT MATCHED THEN
                         INSERT (mac_address, hostname, ip_address, last_seen)
-                        VALUES (?, ?, ?, NOW());
+                        VALUES (?, ?, ?, ?);
                 """;
-
-        jdbc.update(sql, macAddress, hostname, ipAddress, macAddress, hostname, ipAddress);
+        jdbc.update(sql, macAddress, hostname, ipAddress, t, macAddress, hostname, ipAddress, t);
```
Comment (Pdoxxy) [inline backend/src/main/java/kg16/demo/model/Services/ScanService.java:42]: Maybe add try / catch around the updates to catch and log error msgs better.

File: backend/src/main/java/kg16/demo/model/services/TrackerService.java
Comment (Pdoxxy) [inline backend/src/main/java/kg16/demo/model/services/TrackerService.java:1]: Border case of SRP where we could break out a DeviceStatusService that tracks and checks devices.

File: backend/src/main/java/kg16/demo/model/services/TrackerService.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        System.out.println("Unflagged devices: " + unflaggedDevices);
+
+        // Step 2: Flag as offline in the OfflineEvents table
+        for (SummarizedDevice device : unflaggedDevices) {
+            String sql = """
+                        INSERT INTO OfflineEvents (mac_address, offline_since)
+                        VALUES (?, ?)
+                    """;
+
+            jdbc.update(sql, device.macAddress, device.lastActive());
```
Comment (Pdoxxy) [inline backend/src/main/java/kg16/demo/model/services/TrackerService.java:41]: Consider try / catch

**Review by Pdoxxy — APPROVED** [review]
Overall nice code. Could benefit of some error handling and a refactoring of large classes. But approved for now.

File: backend/src/main/java/kg16/demo/model/Services/ScanService.java
[the remark this answers is not in the document]
Comment (hxkhan) [reply backend/src/main/java/kg16/demo/model/Services/ScanService.java:1]: Could possibly be an issue for the coming sprint!
